### ISSUE TITLE
Data layer needs information on "Exposure Scenario"

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#2]
We may have data layers for hazards according to different projections (e.g. "pessimist/optimist climate change projections). We may also have different projections for the exposure (e.g. Stockholm green/black city projections). And we may have also "future extreme weather" (please ask Giulio for correct naming convention) data layers in the data package.

The CSIS system has to be able to differentiate between these variants in order to correctly present them to the user. See our mock-ups for examples on how this could be used.

**Comment by maesbri** [comment]
Yes!  I thought of that too. 
I saw two options, either use the keywords property to indicate to which specific scenario the resource (within the data package) refers to or have a specific  scenario property.

Since we are extending the Data Package specification I think it is better to add the scenario property (with possible fixed values business as usual (bau), pessimist and optimist - correct me if I am wrong with the names).

These values should again, be part of the taxonomy, so there is no possibility to use alternative values and facilitates interpreting the metadata.

**Comment by p-a-s-c-a-l** [comment]
OK, first we have to make sure that we are talking about the same things. The climate change projections you are talking about refer to the **Emission Scenarios** (RCP). The *[Analysis Context](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A42:B42)* of the [Data Package Resource Specification](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484) supports the *[scenario property](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484)* (Note: Possible values should extended by 'current' to allow comparison with current climate):

Name | Type | Multiplicity | FrictionlessData | CSIS  | Description
-- | -- | -- | -- | -- | --
scenario | String enumeration | 0... 1 | N/A | OPTIONAL (*) | Possible values: rcp26, rcp45, rcp85<br/>Note: This property is MANDATORY if the resource is an index

So IMHO, this is already supported in the Data Package specification. And it is already implemented in the CSIS Drupal System:

![grafik](https://user-images.githubusercontent.com/1788226/48856109-dbf61080-edb5-11e8-972f-6969d7816497.png)

**Comment by p-a-s-c-a-l** [comment]
Regarding the **future Exposure Scenarios** I think we have decided that is **not supported in automatic screening mode** as it will not lead to credible results (especially in combination with adaption options which change exposure, too!) I think this can be confirmed by the @clarity-h2020/science-support-team  

So this particular Mock-Up, which lets the user **directly** modify the exposure in simple screening study (as opposed to indirectly by adaptation options) is obsolete:

![grafik](https://user-images.githubusercontent.com/1788226/48855312-1ced2580-edb4-11e8-9ce4-1ac4abf2e1b2.png)

**However**, if credible and realistic future exposure projections are of provided as part of a **tailored Data Package** (e.g. for DC2), we have to support this. So this Mock-Up is valid (despite the fact that here Emission and Exposure Scenario are thrown together!)

![grafik](https://user-images.githubusercontent.com/1788226/48856887-e1ecf100-edb7-11e8-9fc2-686328180750.png)

For supporting Future Exposure Scenarios, we can IMHO created several Exposure Resources with different *[Temporal Context](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A33:B33)* of the [Data Package Resource Specification](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484)'s *[extent property](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit#gid=71709484&range=A38)*:

Name | Type | Multiplicity | FrictionlessData | CSIS  | Description
-- | -- | -- | -- | -- | --
extent | List of two dates or year values: [start, end] | 1 | N/A | MANDATORY | The temporal extent property defines the global temporal extent of all the indicator values present in the dataset. This is the start and the end marks of the union of all the time periods covered by the indicator values. For example, if the indicator values existing in the dataset cover the years 2005, 2006, 2007 and 2008, the temporal_extent property must have the value [2005, 2008].

This already partially implemented in the CSIS Drupal System (@clarity-h2020/drupal-team: exten**t** doesn't yet support 2 dates to define a time period):

![grafik](https://user-images.githubusercontent.com/1788226/48861820-d5bb6080-edc4-11e8-98cd-27fdffa074a1.png)

If it is (always?) the case that a Future Exposure Scenario is linked to a particular Emission Scenario (as suggested in Mock-Up), then we have to use the *analysis_context/resource* property mentioned in [my comment above](https://github.com/clarity-h2020/data-package/issues/2#issuecomment-440736019) for **Exposure Resources**, too. This question can only be answered by @clarity-h2020/dc2 and @clarity-h2020/science-support-team!

In any case, we should very carefully keep an eye on complexity and usability of the system when dealing with different time periods and Exposure / Emission Scenarios since impact need then to be calculated (and [visualised](https://github.com/clarity-h2020/scenario-analysis/issues/7)!) for *n* Emission Scenarios **X** *n* Emission Scenario time periods **X** *n* Exposure Scenario time periods, yet not taking different adaption scenarios into account!  

So @clarity-h2020/mathematical-models-implementation-team that intends to implement the impact model(s) should be aware that it's not just H**x**E**x**V but possibly H<sub>*ij*</sub> **x** E<sub>*i*</sub> **x** V and with adaptation options applied maybe H<sub>*ijk*</sub> **x** E<sub>*i*</sub> **x** V<sub>*i*</sub> ! 😱

**Comment by p-a-s-c-a-l** [comment]
According to [Clarity Hazards Climate Indices.xlsx](//repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP3%20Science%20Support/T3.2%20Climate%20Intelligence/Clarity_Hazards_Climate_Indices_2018_08_05.xlsx), Science Support will provide each hazard index for 3 Emission Scenarios and 4 time periods. This gives us already already 12 combinations (without possible variations in Exposure) for each index. According to [this presentation](//repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/Events/Project%20Events/Plenary%20Meetings/2018-11_14-16%20Project%20Meeting%20%28Madrid%29/Day2%20-%20WP3/CLARITY_WP3_v0.3.pptx) there are additionally 16 GCM/RCM climate model combinations!

Following agile [KISS](https://en.wikipedia.org/wiki/KISS_principle) and [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) principles and to keep the system usable for non-(climate)-Expert users, for the [CSIS v1](https://github.com/clarity-h2020/csis/milestone/9) and possibly for Screening Mode in general we have to (pre) select one Emission Scenario and one time period for impact calculation of the baseline scenario if the Data Package allows different combinations. Agreed @clarity-h2020/mathematical-models-implementation-team ?


Though, we might visualise the available combinations in the HC and EE Steps as shown HC Table Mock-Up (note that the mock-up does not consider different time periods or even different Climate Models!):

![grafik](https://user-images.githubusercontent.com/1788226/48939931-2db5ac80-ef16-11e8-9d47-a2d9f8d69969.png)

**Comment by DenoBeno** [comment]
> Since we are extending the Data Package specification I think it is better to add the scenario property (with possible fixed values business as usual (bau), pessimist and optimist - correct me if I am wrong with the names).
> 
> These values should again, be part of the taxonomy, so there is no possibility to use alternative values and facilitates interpreting the metadata.

I am not sure if it's as simple as that. I do like the idea of defining the bau/optimist/pessimist in taxonomy, but I am not sure if this would be enough. If we end up needing 234 entries in this taxonomy, it's the same as the free text tag. If we can live with just a few entries, a controlled vocabulary (taxonomy)  would be great.

**Comment by DenoBeno** [comment]
> According to [Clarity Hazards Climate Indices.xlsx](//repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP3%20Science%20Support/T3.2%20Climate%20Intelligence/Clarity_Hazards_Climate_Indices_2018_08_05.xlsx), Science Support will provide each hazard index for 3 Emission Scenarios and 4 time periods. This gives us already already 12 combinations (without possible variations in Exposure) for each index. 

3 emission scenarios are good, we can easily show this in a table. 4 Time periods are something to think about. Show 4 tables? Let the user choose one period and then show the table for this period?

We can update the mockup, but how will the user really use this? Should we force the user to choose ONE scenario and one time slot for the whole study? Should we let them experiment with different combinations and include in a report those they deem interesting? 

The same issue will arise again for exposure. In local data package for Stockholm, we will probably have the "current" data and the "green" and "black" projection for several future dates. And in the impact/risk section, we will then have to deal with three future hazard scenarios, two future exposure scenarios and several future dates.

In my opinion, we need to either allow users to choose the "interesting" combinations in the project definition step or to allow them to browse through all combinations in later steps and decide which ones to save in the report.

**Comment by p-a-s-c-a-l** [comment]
Taxonomy terms are least of our problems, @clarity-h2020/mathematical-models-implementation-team should reply to [my comments](https://github.com/clarity-h2020/data-package/issues/2#issuecomment-440768034) above.

**Comment by DenoBeno** [comment]
> Regarding the **future Exposure Scenarios** I think we have decided that is **not supported in automatic screening mode** as it will not lead to credible results (especially in combination with adaption options which change exposure, too!) I think this can be confirmed by the @clarity-h2020/science-support-team

etc. 
First, we can not expect to have future exposure scenarios for the whole europe. So that's indeed not possible to do with the basic data package. We might have future exposure information in local data packages for e.g. Napoli, Stockholm, Linz and then the system needs to deal with this.

This said, I noticed that we have one approach for showing the overview of hazards and a different approach for exposure shown in the mockups. 

- In the hazards, we have a table that appears to be only for one date and thus we would have to either force the user to decide on the date in advance or add a possibility to choose the date (e.g. pull-down)
- In the exposure, we have a table & diagrams showing future development, and user has to choose scenario

Maybe we should allow both variants and let the users decide what they want in their reports? In some cases this would degrade as only one option is available...

**Comment by DenoBeno** [comment]
> Taxonomy terms are least of your problems, @clarity-h2020/mathematical-models-implementation-team should reply to [my comments](https://github.com/clarity-h2020/data-package/issues/2#issuecomment-440768034) above.

I don't know how this works.. Did they get an e-mail notification now, because you mentioned them with @? Or do we need to somehow re-post the question in appropriate forum now?

**Comment by DenoBeno** [comment]
Btw, I am not sure what you mean by "emission scenario". 

Future exposure scenario is mainly a result of planned or unplanned population development and related development of infrastructure. Which scenarios are available will depend on the region. For Stockholm we have heard about "black" and "green" city scenarios, but we could just as well have "rapid expansion", "slow growth", "(de-)industrialization", "everyone moves to suburbs", "more people in the city centre" or any other scenario that the local planners have a reason to advertise.

**Comment by p-a-s-c-a-l** [comment]
> Did they get an e-mail notification now, because you mentioned them with @

yes


> Btw, I am not sure what you mean by "emission scenario".

- rcp26: Early Response
- rcp45: Effective Measures
- rcp85: Business as usual
