### ISSUE TITLE
(How) can we visualize the data in resource node and in the data package node?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#26]
I just noticed a ticked stating that that react components (data visualization widgets) need to be somehow changed (ticket in "map-component -  #https://github.com/clarity-h2020/map-component/issues/37).

This reminded me that _it would be good to imediately visualize the contents of the resource and/or data package outside of a study_. One advantage of this woudl be that the users who are adding resources/data packages would have imediate feedback on what they did and know if they did it correctly or not. Another would be that we would have a simpler & more flexible way to visualiize the data on the site - not hard coded for the needs of the study.

**(1) How to add visualization widgets to nodes?**

Adding a visualization widget to a dp_ressource and other node types would be relatively easy to do. Two possibilities:

1. Write an "Entity View Attachment" view that finds the necessary visualization widget and embeds it in the dp_resource display
2. Let the user defining the resource also choose a visualization. This could be done by defining the visualization nodes containing the javascript applicaitons first and then letting the user choose one or more of them with an entity briwser and linking them to the resource node. 

I can easily add such functions, the only problem is this:

**(2) How do our widgets know what data to show?**

Ideally , our "visualization widgets" would be exactly the same for resources, for data packages and for the studies. Let's take the map widget for example: 

1. How does it know what to show when displayed on a specific place in the study today?
2. How could we make this more flexible so that the same widget can be also used in dp_resources, in dp_package or wherever else we need it?

I'm afraid that today they are looking at the path where they were called and then do some magic to get the relevant data for displaying it today. If they would e.g. look for some hidden variables on the page where they were called, it would be easier to make them work wherever necessary.

Example: a map widget could be passed the bounding box and a list of the resource node IDs and then show all the map layers from al lthe resources that it got at initialization time.

WDYT?

**Comment by p-a-s-c-a-l** [comment]
The Map Component needs a study. It fetches the study area from the JSON API extracts the **study area**, **EMIKAT internal ID** of the study, and the data package resources relevant for the the current step. So, without study, no map.

**Comment by DenoBeno** [comment]
That's unfortunate.

**Comment by DenoBeno** [comment]
What's interesting is that resources have a spatial_extent variable - we just aren't using it. And it's not a geofield.

For testing, I have added a geofield  field "bounding box". Unfortunately, there is no widget to edit it on a map like https://boundingbox.klokantech.com/. Or maybe there is, but it's in "alpha" https://www.drupal.org/project/leaflet_widget

So I entered some data per hand and the result is in principle OK
![image](https://user-images.githubusercontent.com/2961790/62374539-7a896280-b53c-11e9-8c60-85eb6067e1c7.png)

This field *could* be used to initialize any map view, but entering the data is a PITA. 

Hiding it again - until better times...

**Comment by p-a-s-c-a-l** [comment]
Unfortunately, the spatial extent is not enough. When retrieving data from the [EMIKAT APIs](https://github.com/clarity-h2020/emikat/milestone/2), we need a `$emikat_id` which is an equivalent of the `$study_id`. Some or even all data in EMIKAT is generated on the fly for each new study. So we cannot access it from outside the context of a study.

**Comment by p-a-s-c-a-l** [comment]
In principle, this feature is now available. However, in order to activate it, I need access to data package uuid, resource uuid, etc. in the CSIS helpers Module. ATM I can just access the fields of the study group node. See https://github.com/clarity-h2020/csis-helpers-module/issues/10#issuecomment-524820483

Furthermore, the respective Maps (node type: Extended iFrame)  have to be included in the View Mode Forms. I tried it with the [default study group edit form](https://csis.myclimateservice.eu/admin/group/types/manage/study/form-display), which is usually not used by end users:

![grafik](https://user-images.githubusercontent.com/1788226/63695785-a9cc8000-c819-11e9-9c35-3bb3720cc14d.png)

But in the edit form, the map is not rendered automatically:

![grafik](https://user-images.githubusercontent.com/1788226/63696020-22cbd780-c81a-11e9-911b-f789757ca32c.png)

Anyway, [this](https://csis.myclimateservice.eu/apps/map-component/build/GenericMap/?host=https://csis.myclimateservice.eu&study_uuid=3f3a0772-5d55-4f5b-9c7f-fe0a2321d11d&study_area=POLYGON%20((17.914249%2059.250865,%2017.914249%2059.403238,%2018.247265%2059.403238,%2018.247265%2059.250865,%2017.914249%2059.250865))&study_datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&study_emikat_id=3180&grouping_tag=taxonomy_term--eu_gl) is a map that shows **all** WMS Resources available in a data package **that is associated with** the study *3f3a0772-5d55-4f5b-9c7f-fe0a2321d11d*.  If https://github.com/clarity-h2020/csis-helpers-module/issues/10#issuecomment-524820483 has been implemented, we can add such maps to data packages and single resources.

**Comment by DenoBeno** [comment]
I took a look at this, and I feel that we may need @fgeyer16  here.

The preview is based on this node: https://csis.myclimateservice.eu/node/1032

The preview node can be included in a group, as shown here: https://csis.myclimateservice.eu/group/17/edit

![image](https://user-images.githubusercontent.com/2961790/63761488-8bba5a80-c8c1-11e9-8efb-339c9fb8c80f.png)

However, the preview of rendered entity in edit mode doesn't seem to work at all. E.g.:

![image](https://user-images.githubusercontent.com/2961790/63761593-b9070880-c8c1-11e9-991a-198a00f81031.png)

![image](https://user-images.githubusercontent.com/2961790/63761648-cde39c00-c8c1-11e9-9da4-d44368ba161d.png)

I suppose @fgeyer16 would need to look at this.

Map works OK in standard view mode. I have enabled it now in the data view mode of the group

![image](https://user-images.githubusercontent.com/2961790/63764507-4436cd00-c8c7-11e9-817a-afd31d004ef1.png)

@therter , @p-a-s-c-a-l : could you add a title of a currently active map layer in the view?

**Comment by DenoBeno** [comment]
I have tried to do the same with the data package, but it's currently not loading any layers.

See e.g. https://csis.myclimateservice.eu/node/682

**Comment by p-a-s-c-a-l** [comment]
> I have tried to do the same with the data package, but it's currently not loading any layers.

Yes, because there still only the study id available in `$entityInfo' of CSIS helpers. See https://github.com/clarity-h2020/csis-helpers-module/issues/10#issuecomment-524820483

> I have enabled it now in the data view mode of the group

Do you really want to show the map with **all** layers available? Because the layers are context dependent shown in the different steps, too.

> could you add a title of a currently active map layer in the view?

No, that's not possible. Information on selected layers is not available in this context (3rd party library).

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : i have enabled it as a proof of concept. In my opinion, it would make far more sense to have this in the data package (in resource?) than in the study, but I added it to demonstrate that it works.

**Comment by DenoBeno** [comment]
I understand that this should more or less work now?

**Comment by p-a-s-c-a-l** [comment]
yes
