### ISSUE TITLE
assesment on scripts goals

### ISSUE THREAD

**Issue by negroscuro** [clarity-h2020/data-package#3]
I would like PLINIVS to take a look on the scripts to be sure I am doing things as expected.

**Comment by negroscuro** [comment]
I also need BBO Napoli to include it as a parameter and reduce the extracted data area from Urban Atlas since scripts are not supporting it right now.

**Comment by p-a-s-c-a-l** [comment]
You should create another repository and upload the scripts. Maybe somebody else with experience in geospatial data processing (e.g. @Itsman-AT) can help. 

A repository is needed anyway, since I want to *"[cite](https://guides.github.com/activities/citable-code/)"* the scripts in the Data Management Plan to indicate provenance / lineage of Hazard LE Data that is produced by CLARITY and must be [made available in an open data repository](https://github.com/clarity-h2020/ckan/issues/9).

**Comment by p-a-s-c-a-l** [comment]
Repository is available here: https://github.com/clarity-h2020/local-effects
