### ISSUE TITLE
"Include in Report" functionality is blocked by CORS policy

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#31]
Please add the Access-Control-Allow-Origin header to the meteogrid wms, because at the moment we get the following error, when an image of a map with overlay layers from the meteogrid wms will be created.

`No Access-Control-Allow-Origin' header is present on the requested resource`

**Comment by ghilbrae** [comment]
So you can see the layers but not add them to a report? 

Can you please send me a link or something so I can test it? I'll let you know when it's working.

**Comment by therter** [comment]
> So you can see the layers but not add them to a report?

Yes

> Can you please send me a link or something so I can test it? I'll let you know when it's working.

Open the url https://csis.myclimateservice.eu/study/1/step/2/view/maps , add an overlay layer to the map and click on the "Include in Report" button. The created image will be shown on the Summary tab. 
But I am not sure, if the preparations are done on the csis server.

@patrickkaleta:  Have you already set the allowTaint and  useCORS options on the server, so that @ghilbrae can test the button?

**Comment by patrickkaleta** [comment]
@therter yes, I already added the allowTaint option to our button.

@ghilbrae, @therter  
![cors-error](https://user-images.githubusercontent.com/42167036/62199762-626ee300-b384-11e9-88d1-b9d04c57544c.png)
Above you see the error messages (1. and 3. ones mention the CORS settings) I receive when selecting a layer and clicking the "Include in report button". Opening the mentioned [link](https://clarity.meteogrid.com/geoserver/clarity/wms?service=WMS&request=GetMap&layers=clarity%3ATx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3&styles=&format=image%2Fpng&transparent=true&version=1.1.1&width=1536&height=1536&srs=EPSG%3A3857&bbox=1565430.3392804097,4950673.447974297,1624133.9770034251,5009377.085697314) in a separate browser tab works without any problems.

However, I'm not fully sure if there is any action required from @ghilbrae, since I'm able to use hmtl2canvas with that mentioned link in this [CodePen example](https://codepen.io/Onlylonger/pen/ppjPKX) I found, which addresss the same problem we have. Just change the source attribute to one of the meteogrid-links we use and you'll see that it is able to get the requested resource (CodePen example uses same html2canvas version we are, I checked that).

So, my believe is that we need to configure the CORS settings on our server. I'm not an expert on that kind of server configuration, so maybe @Itsman-AT can take care of that?

**Comment by ghilbrae** [comment]
OK, just let me know. I will not change anything until you're positive that I need to change the server config.

**Comment by p-a-s-c-a-l** [comment]
Layers are loaded by leaflet.js XHR request, so it's not the same as the code pen example.

For EMIKAT WMS layers it worked after Heinrich [added the CORS](https://github.com/clarity-h2020/emikat/issues/14) header to EMIKAT WMS, right @thorsten?

So @ghilbrae just has to add the same header on the METEOGRID Geoserver, that's all. No changes to CSIS configuration required.

**Comment by Itsman-AT** [comment]
> 
> So @ghilbrae just has to add the same header on the METEOGRID Geoserver, that's all. No changes to CSIS configuration required.

So, no action required for the server config at AIT?

**Comment by therter** [comment]
> For EMIKAT WMS layers it worked after Heinrich [added the CORS](https://github.com/clarity-h2020/emikat/issues/14) header to EMIKAT WMS, right

Yes, I have tested this locally and it worked with the CORS headers

**Comment by humerh** [comment]
I added (activated) the following lines in the file (Tomcat)/webapps/geoserver/WEB-INF/web.xml:

```

>    <filter>
>         <filter-name>CorsFilter</filter-name>
>         <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
>        <init-param>
>            <param-name>cors.allowed.origins</param-name>
>            <param-value>*</param-value>
>        </init-param>
>        <init-param>
>            <param-name>cors.allowed.methods</param-name>
>            <param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
>        </init-param>
>        <init-param>
>            <param-name>cors.allowed.headers</param-name>
>            <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers</param-value>
>        </init-param>
>        <init-param>
>            <param-name>cors.exposed.headers</param-name>
>            <param-value>Access-Control-Allow-Origin,Access-Control-Allow-Credentials</param-value>
>        </init-param>
>        <init-param>
>            <param-name>cors.support.credentials</param-name>
>            <param-value>true</param-value>
>        </init-param>
>        <init-param>
>            <param-name>cors.preflight.maxage</param-name>
>            <param-value>10</param-value>
>        </init-param>
>     </filter>
>

``` 

plus:

```
>    <filter-mapping>
>         <filter-name>CorsFilter</filter-name>
>         <url-pattern>/*</url-pattern>
>     </filter-mapping>
> 
```

**Comment by ghilbrae** [comment]
@therter this should be working now. Let me know if you still have any problems.

I've tested the map you pointed out and the "report button" has worked just fine.

**Comment by therter** [comment]
@ghilbrae your service works fine now. 
There is still another problem, but that has nothing to do with your WMS and can be fixed by @patrickkaleta and me

**Comment by therter** [comment]
Since the other problem has nothing to do with the CORS policy, we can close this issue.
