### ISSUE TITLE
Error when saving the European-wide data package

### ISSUE THREAD

**Issue by RobAndGo** [clarity-h2020/data-package#48]
I have created a resource by duplicating an existing resource in the European-wide data package, but when I try to save the data package, I get the following error:

![2019-09-17_094316](https://user-images.githubusercontent.com/45385637/65021582-b1220d80-d92f-11e9-9684-bd94edb1597f.png)

The error seems to suggest a "duplicate key" already exists. I checked the data package and the resource I added does not already exist in the data package. However, I did previously add it some weeks ago, but then it disappeared when @DenoBeno reset the DB back to an older backup (see [here](https://github.com/clarity-h2020/docker-drupal/issues/107)).

I have tried now to add a resource which I hadn't previously updated, and I get the same error.

![2019-09-17_102135](https://user-images.githubusercontent.com/45385637/65024343-f563dc80-d934-11e9-86b4-ef48b6eac88b.png)

**Comment by DenoBeno** [comment]
Hm. 
The european data package already has *too many* resources, I wonder if this could be causing it. There is a data package the patrick uses for testing, this one: https://csis.myclimateservice.eu/node/50

So, let me try... 

1. https://csis.myclimateservice.eu/node/50/edit spawns the JSON:API error that I keep seeing lately. It seems harmlos, but let me just mention it here: 

![image](https://user-images.githubusercontent.com/2961790/65039791-57333f00-d953-11e9-8273-44d3af8026d5.png)

2. I already have this resource linked in the data package:
![image](https://user-images.githubusercontent.com/2961790/65039837-703bf000-d953-11e9-8b11-02812283caac.png)

3. Trying to duplicate it....

![image](https://user-images.githubusercontent.com/2961790/65039956-a7120600-d953-11e9-85a9-ccc24191e0fb.png)
...
![image](https://user-images.githubusercontent.com/2961790/65039992-b729e580-d953-11e9-8267-80858cadfde7.png)

That worked without error

4. Trying to save the data package...

![image](https://user-images.githubusercontent.com/2961790/65040079-e50f2a00-d953-11e9-8aa3-b4f0fe0499e3.png)

No error..

![image](https://user-images.githubusercontent.com/2961790/65040112-f2c4af80-d953-11e9-9e95-0b93214c4d5a.png)

5. back to edit mode, the resource is in the DP:

![image](https://user-images.githubusercontent.com/2961790/65040165-0bcd6080-d954-11e9-9518-d6f14af6651f.png)

Looks OK to me. I don't know if I'm just overly paranoid, but we have over 100 resources in european DP. I am afraid that we may be hitting some limit here.

**Comment by RobAndGo** [comment]
Would it make sense to define separate data packages as "European Wide Data Package Heat" and "European Wide Data Package Flood" in order to accommodate all of the indices?
I suppose this would assume that the user is only interested in one or the other hazard types.

Alternatively to save on the number of resources, @DenoBeno would it be possible for me to combine the ..._ensmean and ...._ensstd into one resource and add a path for each to the "Download paths" and "Service paths" so that there will be 2 paths defined for each category. Is this the purpose for allowing one to specifiy more than one path here? Doing this would halve the number of hazard indices.

I have tested this with the newly inserted resource: PI_consecutive-wet-days_rcp26_20110101-20401231
Here I have included both the _ensmean and _ensstd within it.

**Comment by RobAndGo** [comment]
I tried again to duplicate a resource and save the data package, and it worked! When duplicating the resource this time, I just changed the title and kept everything the same. Last time when I duplicated the resource and it didn't work, I changed all relevant fields (e.g. ckan link, description, tags, download path, service path).

**Comment by DenoBeno** [comment]
Ah yes, it's the best approach to just change the title, save and then go back to edit. 

In my opinion, we should leave the european data package "as is" in terms of the heat resources for now and definitely not attempt adding all the flood resources to it. Ever. 

In the meantime, we can build a "screening 2" data package where the resources are defined so that they use variables. Ideally, the flood hazard data would only be added to that new data package, while the old one would be eventually phased out. If  we manage to support the resources with variables in the next few weeks, this will be all we need. If not, I don't know what to do. Adding even more resources to European DP is a major PITA, but making a new one for floods would be just as bad. :-(

**Comment by DenoBeno** [comment]
> I tried again to duplicate a resource and save the data package, and it worked! When duplicating the resource this time, I just changed the title and kept everything the same. Last time when I duplicated the resource and it didn't work, I changed all relevant fields (e.g. ckan link, description, tags, download path, service path).

Conclusion: this is a relatively minor bug that is mildly annoying but doesn't stop us from working. I do not plan to handle this now - removing the "showstopper" and putting it on hold.

**Comment by p-a-s-c-a-l** [comment]
> If we manage to support the resources with variables in the next few weeks,

Let's concentrate on having a presentable and working system for European Week of Regions and Cities  (7-10 OCTOBER 2019) first and then we can restart this discussion. 

BTW, resources with variables are not as easy to handle as you might imagine , e.g. think about resource titles which are used as layer names, ckan ids, export/import of data package meta-data according to frictionless data package standard , etc. So we shouldn't introduce more [accidental complexity](https://www.nutshell.com/blog/accidental-complexity-software-design/) into the system as we are able to handle atm.

**Comment by DenoBeno** [comment]
> > If we manage to support the resources with variables in the next few weeks,
> 
> Let's concentrate on having a presentable and working system for European Week of Regions and Cities (7-10 OCTOBER 2019) first and then we can restart this discussion.
> 
> BTW, resources with variables are not as easy to handle as you might imagine , e.g. think about resource titles which are used as layer names, ckan ids, export/import of data package meta-data according to frictionless data package standard , etc. So we shouldn't introduce more [accidental complexity](https://www.nutshell.com/blog/accidental-complexity-software-design/) into the system as we are able to handle atm.

"let's concentrate on short-term priorities" is something I can easily agree with.

The second part, I don't understand. You will have to handle variables because EMIKAT resources depend on this. And there are EMIKAT resources in several GL steps, so this will have to be rather generic from the start.

Not letting the user decide which combinations are to be used certainly simplifies a design a bit, so I understand that. But in order to use the variables with EMIKAT resources you will have to resolve all the issues that you are mentioning above. The way I see it:

- layers labels will have to be built from the title + variable values. This is how we are already calling the resources today, only we do it manually and with tons of duplication now.
- ckan resources will have to be merged too. Instead of a zylion of them, there will be one covering all possible combinations. Either that or we allow linking to more than one CKAN entry.
- frictionless data package standard is the least of my problems. I suppose that we could think of generating a zylion of resource descriptions from one dp_resource by expanding all possible combinations of the variables on the fly and spitting out the correct json. We could even put a ticket for this, but how urgently do we need this?

**Comment by DenoBeno** [comment]
I suppose we aren't going to do anything about this? Users should be careful when duplicating the resources and that's it.
