### ISSUE TITLE
Visualisation of data on the map - best practices

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#53]
Related to:  https://github.com/clarity-h2020/data-package/issues/8#issuecomment-542592439_

We are often running into a problem with data visualisation. Two main reasons:
1. Scale.
2. Colour coding.

Recommendations:
1. Use the same scale and color coding for all the variants of the same indicator, at least within one study. E.g._
  - The "number of heat days" hazard indicator should have the same scale for the past climate and for the various future climate predictions, for 1 year, 5 year and 20 year frequency.
2. Assure that the scale has high contrast so that the users can recognise the changes on the map. E.g.:
  - scale that only uses yellow/brown/red is less usable than one that also uses green and blue
  - scale that uses blu(ish) color at two ranges of values will confuse the users.
3. Choose the scale wisely, so that:
  - the "interesting" parts of the continent do show some cahanges of color. For example, all of France should definitely not be the same color.
  - the difference between tome periods, emission scenarios, emission scenario etc. should be visually obvious.

**Comment by DenoBeno** [comment]
Some examples of badly chosen scales:

1. Hot days: almost half of the scale is bluish. Furthermore, the two blue strips can't be differentiated.

Past climate
![grafik](https://user-images.githubusercontent.com/2961790/67201085-c3e3a280-f405-11e9-8c19-d0d8d2329c3d.png)
Worst case future
![grafik](https://user-images.githubusercontent.com/2961790/67201456-a2cf8180-f406-11e9-89f3-40e60d984833.png)

2. Hot days, standard deviation: scale is way out of bounds.  Anything beyond 10 is probably to be considered "junk data", so the contrast should be somewhere in the 0-10 or maybe 0-2 scale.
![grafik](https://user-images.githubusercontent.com/2961790/67201950-bfb88480-f407-11e9-8968-a1eb5fa5f3c9.png)

3. No green & blue colors used => less contrast available

![grafik](https://user-images.githubusercontent.com/2961790/67202047-03ab8980-f408-11e9-89ef-0b8b6cea936f.png)

**Comment by DenoBeno** [comment]
For EMIKAT, I have noticed that scales for the heat indices are not good. E.g. the Ageos dimitrios study:

historic data, yearly events
- T_MRT = 74 to 103 °C
- T_UTCI = 51 to 58 °C
- T_amb = 35 to 41 °C
Worst case, 20 years events
- T_MRT = 86 to 114 °C
- T_UTCI = 63 to 70 °C
- T_amb = 43 to 49 °C

Forr all three indices, the scale is the same, 20-100°C, although T_MRT never goes below 74°C and T_ambient never above 50°C. Consequently, almost nothing is seen on a map.

E.g. T_UTCI:
![grafik](https://user-images.githubusercontent.com/2961790/67203227-e2986800-f40a-11e9-8164-c529f35afb68.png)

The green-yellow-red scala used here is not bad by the way. We could use this and add lila & blue below green and brown above red for even more contrast.

**Comment by LauraMTG** [comment]
Hi @DenoBeno 

Considerations 

The initial selection of the scale is certainly random, since its availability in geoserver was massive. I will now make some points that are already being taken into account: 

1- Use the same scale and color coding for all variants of the same indicator, at least within a study. 
Make sure the scale has a high contrast so that users can recognize changes in the map. E.g:
**Yes, these two points have already been started. You can check this in the following layers: HI_summer-days...**
Two base legends have been made for media and desviation layers that are applied to the whole equally for ease of comparison.
2- the scale that only uses yellow / brown / red is less usable than one that also uses green and blue.
**However, when the variable that is represented alludes to hot days, the green or blue color is really confusing and not advisable. Therefore this recommendation is not always applicable.**

3-**for visual examples 1 and 2, these are not definitive scales. these layers must be updated with the new mask we are considering. Then we proceed to its revision and adjustment of ranges**.

4-**I will consider greater contrast for stakeholders in next steps.**

**Comment by DenoBeno** [comment]
ok, thanks
