### ISSUE TITLE
How are the "possible study area" borders determined?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/data-package#58]
I have just realised that the "Vienna" region contains all of the Neusiedl lake and most of the Bratislava, but not the Bratislava airport. 

![image](https://user-images.githubusercontent.com/2961790/68114551-94995f00-fef6-11e9-9e96-3db2cd757742.png)

Also, we do not offer Slovakia/Bratislava area for the study. Interestingly, this is not aligned with the Urban Atlas 2012 data set:

![image](https://user-images.githubusercontent.com/2961790/68114636-d5917380-fef6-11e9-8a5a-0453b946400c.png)

**Comment by patrickkaleta** [comment]
**To answer the question on how the border is determined:** 
@therter imported the Cities/regions taxonomy from ATOS (created by @negroscuro ) and each city/region has a `bounding box` field that defines the area ([here](https://csis.myclimateservice.eu/taxonomy/term/3390/edit) the entry for Vienna). That bouding box is then displayed by Thorstens map component (which also checks that the selected Study area stays within this bounding box). 

**Why is Bratislava not included as a separate city?** I'm not sure, maybe it doesn't contain all the necessary data that we need for our further calculations and that's why it was left out by @negroscuro ?

**Comment by DenoBeno** [comment]
Actually, the bratislava is included in Vienna region. I don't really care, but the folks form Slovakia will hate us for it.

**Comment by negroscuro** [comment]
Sorry I missed the  issue.

@therter , I had some issues with city layer which was divided into two (city_bbox and city_boundaries) so now Atos Geoserver only provides one, just city. It only includes boundary of the city, so I removed bbox since it is less accurate. Is that ok? or do you need it?
Anyway I think you can keep using Mortality layer since it is importing city layer boundary geometry and city code, indeed it cointains the final available city list.

@patrickkaleta , you were right for Bratislava, there was not all needed data so it is not between the 545 cities loaded. But Wien do so it is in the system as one of those 545 available cities. Anyway the 545 cities now came down to 440 since only the ones with Mortality data are useful for EMIKAT.

@DenoBeno , I was checking boundaries and it seems there are different ones to consider. The base for local effects calculations is Urban Atlas 2012 so the city boundary I use to show in the maps and also all te information of a land use city is taken from such boundary of UA2012 (yellow Wien and Bratislava purple).
That is a shapefile where I extract data (notice there are a lot of geometries within) and mix it with Street Tree Layer data and European Settlement Maps data as well in order to generate final land use data for a city.

What is the problem I recently noticed? is that UA2012 also comes with a second shapefile called boundaries which just one single geometry, the city boundaries (Wien in blue and Bratislava in green) and are much smaller than the UA2012 shapefile, let me show you an screenshot for you to better understand:

![image](https://user-images.githubusercontent.com/6427900/69047116-bb798a00-09fa-11ea-91d1-bf744adbc5fb.png)

In any case notice that Bratislava boundaries are not overlapping with Wien ones so I do not see any problem with that. The problems comes regarding wich boundary of a city to use, If we agree to keep using the big one, nothing changes, but if we decide to move on the smaller, I have to recalculate every city data taking only into account such smaller area and only the goemetries within it. This will ease a lot the calculations and I expect it to take considerably less time in doing so. But I am not the one with the knowledge to take such decision, Maybe @mattia-leone or @RobAndGo, maybe even @humerh  may help us on that. Indeed I am not sure if such question was already discussed with Alessandra, I cannot remember clearly.

So in any case, Bratislava is not overlapping Wien, am I wrong with is? It looks ok to me.

![image](https://user-images.githubusercontent.com/6427900/69047588-d0a2e880-09fb-11ea-8fe3-985d5a99f965.png)

**Comment by DenoBeno** [comment]
The smaller boundaries are Juste the administrative City boundaries.  Not really Import för us.

**Comment by negroscuro** [comment]
Ok then I understand everything is ok as it is right now.
