### ISSUE TITLE
Duplicating an existing data package

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/data-package#60]
Hi! We are wondering if it is possible to duplicate an existing Data Package or if it is a matter of having the correct permissions. Thanks!

**Comment by p-a-s-c-a-l** [comment]
Is it possible to create a *shallow* copy of Data Package entity? @patrickkaleta @fgeyer16

**Comment by patrickkaleta** [comment]
> Hi! We are wondering if it is possible to duplicate an existing Data Package or if it is a matter of having the correct permissions. Thanks!

Currently it's not possible to duplicate data packages, so it's not a permissions issue. Duplicating content is not a default feature of Drupal, but there are modules for Drupal out there, that allow for such a functionality. Problem lies with the complex data structure of our data packages, so I noticed a couple of issues with those modules and didn't further investigate since this feature was always a low priority.

**Comment by patrickkaleta** [comment]
> Is it possible to create a _shallow_ copy of Data Package entity? @patrickkaleta @fgeyer16

Currently also not possible and I don't think that's what we want to have in the end. At least not for every reference in a data package, since that's (e.g. resources) usually what the users will want to edit after duplicating an existing data package.

Since the last time I checked the feasibility of this feature, the data model for data packages has changed again, but seems quite stable now. And (AFAIK) we are not using any paragraphs in the data packages (which make duplicating content difficult) nor are we currentlyplanning to do so...
 
That said, I can look again into duplicating whole data packages and check if it's possible to implement this without much trouble.

**Comment by ghilbrae** [comment]
Thanks @p-a-s-c-a-l and @patrickkaleta that certainly answers my question. The issue is resolved from my side, so I proceed to close it.
