### ISSUE TITLE
Data Packages per study

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/data-package#61]
Is it possible or planned to be able to assign more than one data Package to a study?

Also, same question for resources. In a study can resources from other data packages or resources available in the CSIS be used along the already assigned Data Package?

**Comment by patrickkaleta** [comment]
> Is it possible or planned to be able to assign more than one data Package to a study?

ATM this is not possible and I'm not aware of such plans that would make it possible in the future.

> Also, same question for resources. In a study can resources from other data packages or resources available in the CSIS be used along the already assigned Data Package?

I'm not sure if I understand your question. You can reference a resource in multiple data packages, that's not a problem - adding a resource to a new data package doesn't affect the data packages that already reference (use) that resource. **Just be careful not to edit an existing resource, since that would impact all other data packages as well.** 

If changes are necessary, rather click on the "duplicate" button of the resource, make the changes in the duplicated version, and in the end remove the original resource from your selection, so that your data package only contains the new resource.

**Comment by ghilbrae** [comment]
The second question was going for the possibility of using a resource on its own along with a DP inside the study. 

If the way to go is to add the resource to the DP, then I would like to know if the idea is to have a DP per study or if you can ignore certain resources from a DP within your study.

**Comment by DenoBeno** [comment]
you can ignore them.

**Comment by patrickkaleta** [comment]
> The second question was going for the possibility of using a resource on its own along with a DP inside the study.
> 
> If the way to go is to add the resource to the DP, then I would like to know if the idea is to have a DP per study or if you can ignore certain resources from a DP within your study.

Yes, just like Denis said, unnecessary resources in a data package can simply be ignored. At some later point users will get the option to select only those resources of a DP, which they are interested in.

**Comment by ghilbrae** [comment]
Thanks all for the clarifications.
