### ISSUE TITLE
Is it possible to sort resources within a data-package?

### ISSUE THREAD

**Issue by RobAndGo** [clarity-h2020/data-package#63]
Apologies if this has been covered already and maybe I missed it, but is it possible to sort the resources within a data-package e.g. alphabetically?

I want to edit some of the resources within the "European Wide Data Package", and it seems the entries are just sorted according to when they were inserted. This makes it hard to find things within it.

**Comment by RobAndGo** [comment]
And while I am here, I have noticed that when editing a resource, there are two options:
- Quick edit
- Edit

I understand what "Edit" does, but using "Quick edit" seems a bit unclear. Am I correct in saying that I can only edit 3 fields with this tool (description, spatial extent, and ckan address)?

And there seems to be some bugs with this "Quick edit". I am using the latest version of Chrome for this.
1. When editing the description text box and saving, the word "description" appears in the text box as seen when using the normal "edit" option. Doing this process twice gives two description words:
![image](https://user-images.githubusercontent.com/45385637/73826277-cd024f00-47fd-11ea-9f8f-5690270f065e.png)
2. The inserted text seems to be attached to the last sentence, ignoring any blank lines that I have inserted in between. (see example above with the new text being "Background: This climate index...."

Perhaps it could be useful if, along with these edit options, there is an option to move resource up or down in the resource list?

**Comment by patrickkaleta** [comment]
> Apologies if this has been covered already and maybe I missed it, but is it possible to sort the resources within a data-package e.g. alphabetically?
> 
> I want to edit some of the resources within the "European Wide Data Package", and it seems the entries are just sorted according to when they were inserted. This makes it hard to find things within it.

AFAIK this has not been asked before. You have a couple of options for how to edit resources and depending on the use case, one might be better or less suited than the others:
1)  **Edit a resource via viewing the data package and clicking on the "pencil-icon" of the resource**
So for the European DP it would be this link: https://csis.myclimateservice.eu/node/682
That's probably the worst choice, since the theme is not optimized for viewing a data package and for a big DP like the European one it takes a lot of time to load the page since everything inside the DP is rendered

2) **Edit a resource via the edit form of the respective DP**
Link: https://csis.myclimateservice.eu/node/682/edit
Here you have on the left of each resource title an "drag-icon" which you can use to move the resource up and down. After saving it will keep the new position for the next time you go on the edit form or view the DP like described in 1) (but AFAIK nowhere else on the site will this order have any effects)

3) **Edit a resource via the "Maintenance" tab**
Link: https://csis.myclimateservice.eu/maintenance/datapackages/682 (or click on "Maintenance" -> "Data packages" -> select "more details" for corresponding DP )
On the bottom of the page all linked resources are listed and for each of them you have an edit link on the right, which leads you to the form of the individual resource. (Additionally: on top of the page you can filter resources based on the EU-GL taxonomy)

**In your case I would definitely prefer option 3.** No. 1) & 2) are given in Drupal by default and our possibilities are somewhat limited. This "Maintenance" page was done by ourselves, so we have more control here. I made the table sortable by **title** and **author** (you just have to click on the labels). By default the table is sorted by the date they were last edited.

I hope this will make things easier for you. If not, let me know what else could be improved/added.

**Comment by patrickkaleta** [comment]
> And while I am here, I have noticed that when editing a resource, there are two options:
> 
> * Quick edit
> * Edit
> 
> I understand what "Edit" does, but using "Quick edit" seems a bit unclear. Am I correct in saying that I can only edit 3 fields with this tool (description, spatial extent, and ckan address)?
> 
> And there seems to be some bugs with this "Quick edit". I am using the latest version of Chrome for this.

Well, Drupal has this "Quick edit" to make life more comfortable and let you edit content directly in the front end where it appears (called View-mode in Drupal), so that you can see immediately how it will look, instead of sending you to the form of that content type (aka Edit-mode). **BUT** as you already noticed it has quite a few bugs, so I wouldn't use it, especially not with so complex entities like data packages and resources.

I don't know if there is a easy way on how to disable the "quick-edit" to even appear on our site, but for now I would simply stay away from that and always use the normal and working "edit".

**Comment by RobAndGo** [comment]
Thanks @patrickkaleta. 

By the way, what I do **love** with the current edit feature under the "Maintenance tab" is that, when I select "edit" with the right-mouse button, I can **open it in a new browser tab** and still have the list of resources in the original tab. This way, I can quickly edit multiple resources at once and save each individually. AND, I don't need to save the whole data-package at the end in order to keep all changes - I lost count of the number of times I forgot to do this previously and thus lost all of my work! :-(
