### ISSUE TITLE
The layer names should be displayed in the legends

### ISSUE THREAD

**Issue by therter** [clarity-h2020/data-package#71]
In all layers except the clarity background layers, only the units are displayed in the legend. It would be very useful to also display the layer name.

**Comment by DanielRodera** [comment]
Hi @therter, I think @ghilbrae have created the styles you are asking for changes.

**Comment by ghilbrae** [comment]
Both @LauraMTG and I created the styles. The problem with adding the name of the layers is that we are using the same style for several sets of layers and if we add anything more to the legend we need to make sure that other layers using the same style are not affected. We will have to replicate all the styles affected. It is not difficult but it will be a slow and tedious task due to the hundreds of layers that we have.

Let us know how urgent and important this is because we will need some time to do it.

**Comment by p-a-s-c-a-l** [comment]
>  It is not difficult but it will be a slow and tedious task due to the hundreds of layers that we have.

O.K:, I see. Is it perhaps possible to use some kind of *variables* in the SLD definition? Any ideas @therter 

> Let us know how urgent and important this is because we will need some time to do it.

Maybe @claudiahahn  can answer this question :-)

**Comment by claudiahahn** [comment]
It might not be that urgent, because the user can check again, which layer was selected, but it would be very useful to  have it at the end :/
Higher priority should probably be given to a better color scaling and the mouse over feature to display values

**Comment by p-a-s-c-a-l** [comment]
> Higher priority should probably be given to a better color scaling

Do you whether we have a separate  issue for that @claudiahahn ? I  remember the discussion on this topic but I cannot find it any more.

>  and the mouse over feature to display values

O.K:, that is discussed [here](https://github.com/clarity-h2020/emikat/issues/41)

**Comment by ghilbrae** [comment]
I will prepare a list of the styles being used and the layers that use them so we can have a better understanding of how is this working now. Maybe we can find a solution that is not too problematic.

**Comment by therter** [comment]
> Is it perhaps possible to use some kind of _variables_ in the SLD definition?

There are variables, which can be used in SLD documents, but unfortunately it is not possible to use variables within the title element (that is used to define the label in the legend). This is neither in SLD version 1.0.0 nor in version 1.1.0 allowed.

**Comment by p-a-s-c-a-l** [comment]
> but unfortunately it is not possible to use variables within the title element

I don't think that this is necessary. Looking at the [original request](https://github.com/clarity-h2020/csis-technical-validation/issues/53#issuecomment-646655837), its basically just required to include the layer *name* **or** *title* in the legend as described [here](https://gis.stackexchange.com/questions/186535/change-title-of-geoserver-legend-decoration).

**Comment by claudiahahn** [comment]
I think the mouse over feature is discussed here: 
https://github.com/clarity-h2020/csis/issues/163

The color scaling was mentioned several times, also by Denis, but I could not find an issue either

**Comment by p-a-s-c-a-l** [comment]
> The color scaling was mentioned several times, also by Denis

Yes , but without clear requirements we don't know what to change. :-) 

>  I could not find an issue either

Probably it was discussed as part of an 'off topic' discussion in an otherwise unrelated issue. 
Perhaps @RobAndGo and @DenoBeno do remember what was wrong with which styles and where this has been discussed.

**Comment by maesbri** [comment]
> > The color scaling was mentioned several times, also by Denis
> 
> Yes , but without clear requirements we don't know what to change. :-)
> 
> > I could not find an issue either
> 
> Probably it was discussed as part of an 'off topic' discussion in an otherwise unrelated issue.
> Perhaps @RobAndGo and @DenoBeno do remember what was wrong with which styles and where this has been discussed.

For what I remember:
1. The legends of many indexes don't match the measure units, that is, for instance, index is about number of hot days but the map legend refers to temperature degrees (just as an example). All indexes styles should be reviewed to be sure the legend is correct (in WP3 folder there is an excel file with all indexes and the corresponding unit of measure).
2. Colouring. Denis complained that in many legends the colours used are very similar making it difficult to visually distinguish them on the maps.

**Comment by RobAndGo** [comment]
As I do not know how the colour bar legend is implemented in the map view, I will upload an example of a rather pleasing (to me at least) colour scale which can be **used for all heat indices**:
[heat_colourbar.rgb.txt](https://github.com/clarity-h2020/data-package/files/4830381/heat_colourbar.rgb.txt)

It's an ASCII file (remove the temporary .txt extension) and gives the red, green, blue values on a scale from 0-1 for each level. In this case there are 16 colour levels defined (ncolors= 16), and after the comment line (# r g b), the rgb values are defined.
 
To use this for the **cold indices**, one would need to reverse the order on the levels in the file, which I have done here:
[cold_colourbar.rgb.txt](https://github.com/clarity-h2020/data-package/files/4830452/cold_colourbar.rgb.txt)

It comes from this website [here](http://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml) which has lots of examples of colourbars and their corresponding RGB values.

In general, using stepped rather than continuous colourbars make differences easier to see.

**All indices involving precipitation** could use this colour scale:
[precip_diff_12lev.rgb.txt](https://github.com/clarity-h2020/data-package/files/4830437/precip_diff_12lev.rgb.txt)

**Comment by p-a-s-c-a-l** [comment]
O.K. It seems that we cannot change the legend which is returned by `getLegendGraphic` directly but have to provide a separate [WMS Decorations](https://docs.geoserver.org/stable/en/user/services/wms/decoration.html#wms-decoration-types). @DanielRodera perhaps you can give it a try? Without access to the geoserver data dir I cannot check it out myself, but the approach is rather straightforward. This should do the trick:
```xml
<layout>
    <decoration type="legend" affinity="top,left" offset="6,6" size="auto"/>
</layout>
```

@therter If we follow the approach with decorators, we don't need a separate `getLegendGraphic` request, because the legend is directly rendered in the image returned by the getMap! However this works only for layers served from geoserver.myclimateservice.eu, not for layers retieved from external WMS' ("Backgrounds"). Furthermore, it does not make much sense for **HC-LE layers** ("CLARTIY Backgrounds") to show the *name/title* **in addition** to the *labels*. In the end we might end up of with two different legends: on in the image and one as a separate overlay. I don't think that this is a feasible approach as we never can make sure that the external legend does not intersects and overlays with the built-in legend.

**Comment by p-a-s-c-a-l** [comment]
resolved in https://github.com/clarity-h2020/map-component/issues/98
